# Generated by Django 4.2.24 on 2025-09-15 20:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(max_length=50)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_source', models.CharField(blank=True, max_length=200)),
                ('price_source_url', models.URLField(blank=True)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('auto_update_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.CharField(default='Southland', max_length=100)),
                ('currency', models.CharField(default='NZD', max_length=10)),
                ('excludes_gst', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('scrape_interval_hours', models.PositiveIntegerField(default=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_scraping_enabled', models.BooleanField(default=False)),
                ('default_scrape_interval_hours', models.PositiveIntegerField(default=24)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('timeout_seconds', models.PositiveIntegerField(default=10)),
                ('user_agent', models.CharField(default='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36', max_length=255)),
                ('last_global_scrape', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('2_wire_electric', '2 Wire Electric'), ('3_wire_electric', '3 Wire Electric'), ('9_wire_hot', '9 Wire Hot'), ('9_wire_barb', '9 Wire Barb'), ('netting_hot', 'Netting + Hot'), ('deer', 'Deer Fence')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('post_spacing', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('wire_count', models.PositiveIntegerField()),
                ('requires_battens', models.BooleanField(default=False)),
                ('batten_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('requires_insulators', models.BooleanField(default=False)),
                ('requires_strainers', models.BooleanField(default=True)),
                ('requires_energiser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('barb_wire_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='barb_wire_fence_types', to='fence_calculator.material')),
                ('batten_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batten_fence_types', to='fence_calculator.material')),
                ('hot_wire_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hot_wire_fence_types', to='fence_calculator.material')),
                ('netting_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='netting_fence_types', to='fence_calculator.material')),
                ('post_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_fence_types', to='fence_calculator.material')),
                ('wire_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wire_fence_types', to='fence_calculator.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FenceCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fence_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posts_required', models.PositiveIntegerField()),
                ('wire_length_meters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wire_rolls_required', models.DecimalField(decimal_places=2, max_digits=8)),
                ('battens_required', models.PositiveIntegerField(blank=True, null=True)),
                ('labor_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('labor_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_costs', models.JSONField(default=dict)),
                ('total_material_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_overrides', models.JSONField(blank=True, default=dict)),
                ('user_session', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fence_calculator.fencetype')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fence_calculator.material')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fence_calculator.supplier')),
            ],
            options={
                'unique_together': {('material', 'supplier')},
            },
        ),
    ]
