# Generated by Django 4.2.7 on 2025-09-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fence_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='roll_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Roll length in meters (for wire materials)', max_digits=8, null=True),
        ),
    ]
