# Generated by Django 4.2.7 on 2025-09-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fence_calculator', '0002_material_roll_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fencetype',
            name='hot_wire_material',
        ),
    ]
