# Generated by Django 4.2.7 on 2025-10-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fence_calculator', '0003_remove_fencetype_hot_wire_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fencecalculation',
            name='battens_required',
        ),
        migrations.RemoveField(
            model_name='fencetype',
            name='batten_material',
        ),
        migrations.RemoveField(
            model_name='fencetype',
            name='batten_spacing',
        ),
        migrations.RemoveField(
            model_name='fencetype',
            name='requires_battens',
        ),
        migrations.AddField(
            model_name='fencecalculation',
            name='electric_outrigger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fencecalculation',
            name='netting_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fencecalculation',
            name='netting_type',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
